### Death endpoint
POST http://localhost:8080/log-parser/game/1/deaths
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="qgames.log"

< ./qgames.log
--boundary
Content-Disposition: form-data; name="advertType"

--boundary

### Matches endpoint
POST http://localhost:8080/log-parser/game/1/matches
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="qgames.log"

< ./qgames.log
--boundary
Content-Disposition: form-data; name="advertType"

--boundary
